version: '3'

services:
  web:
    image: ruby:2.5.5-buster
    container_name: ruby_app
    command: bash -c "bundle update listen && bundle install && rails s -b '0.0.0.0'"
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:11-buster
    container_name: db
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contacts
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  driver: local
