version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.5-buster-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Update
          command: bundle update listen
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Run test
          command: bundle exec rake
