default: &default
  adapter: postgresql
  encoding: unicode
  database: contacts
  host: localhost
  pool: 5
  username: postgres
  password: admin_12345

development:
  adapter: postgresql
  encoding: unicode
  database: contacts
  host: localhost
  pool: 5
  username: postgres
  password: admin_12345

test:
  adapter: postgresql
  encoding: unicode
  database: contacts
  host: localhost
  pool: 5
  username: postgres
  password: admin_12345

production:
  adapter: postgresql
  encoding: unicode
  database: contacts
  host: localhost
  pool: 5
  username: postgres
  password: admin_12345
